[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  EXPO_TOKEN = "your-expo-token-here"

[[plugins]]
  package = "@netlify/plugin-expo"

[plugins.inputs]
  platform = "android"
  profile = "production"
