version: 2.1

jobs:
  build-android:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npm install -g @expo/cli eas-cli
      - run:
          name: Build APK
          command: |
            eas build --platform android --profile production --non-interactive
            eas build:list --platform android --limit 1 --json > build-info.json
            BUILD_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
            if [ "$BUILD_URL" != "null" ] && [ "$BUILD_URL" != "" ]; then
              curl -L -o "김포도시관리공사-e-캠퍼스.apk" "$BUILD_URL"
            fi
          environment:
            EXPO_TOKEN: $EXPO_TOKEN
      - store_artifacts:
          path: 김포도시관리공사-e-캠퍼스.apk
          destination: android-apk

workflows:
  version: 2
  build:
    jobs:
      - build-android
