name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install

    - name: Setup Expo and EAS CLI
      run: |
        npm install -g @expo/cli eas-cli

    - name: Configure EAS project
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        echo "EXPO_TOKEN is set: ${{ secrets.EXPO_TOKEN != '' }}"
        eas init --non-interactive --force
        echo "EAS project configured successfully"
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build APK with EAS
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        echo "Building APK with EAS..."
        echo "EXPO_TOKEN is set: ${{ secrets.EXPO_TOKEN != '' }}"
        echo "EXPO_TOKEN length: ${#EXPO_TOKEN}"
        eas build --platform android --profile preview --local --non-interactive

    - name: Rename and prepare APK
      run: |
        echo "Preparing APK..."
        mkdir -p artifacts
        cp build/android/app/build/outputs/apk/release/app-release.apk artifacts/gimpo-e-campus.apk
        echo "APK prepared successfully: gimpo-e-campus.apk"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: artifacts/gimpo-e-campus.apk
        if-no-files-found: warn