name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install

    - name: Setup Expo and EAS CLI
      run: |
        npm install -g @expo/cli eas-cli

    - name: Configure EAS project
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        echo "EXPO_TOKEN is set: ${{ secrets.EXPO_TOKEN != '' }}"
        eas init --non-interactive --force
        echo "EAS project configured successfully"
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build APK with EAS
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        echo "Building APK with EAS..."
        echo "EXPO_TOKEN is set: ${{ secrets.EXPO_TOKEN != '' }}"
        echo "EXPO_TOKEN length: ${#EXPO_TOKEN}"
        echo "Creating keystore manually..."
        mkdir -p android/app
        keytool -genkeypair -v -keystore android/app/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
        eas build --platform android --profile preview --non-interactive

    - name: Download APK
      run: |
        echo "Downloading APK..."
        mkdir -p artifacts
        eas build:list --platform android --limit 1 --json > build-info.json
        BUILD_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
        if [ "$BUILD_URL" != "null" ] && [ "$BUILD_URL" != "" ]; then
          curl -L -o artifacts/gimpo-e-campus.apk "$BUILD_URL"
          echo "APK downloaded successfully: gimpo-e-campus.apk"
        else
          echo "No APK URL found"
        fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: artifacts/gimpo-e-campus.apk
        if-no-files-found: warn